global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']

  - job_name: 'materialize'
    static_configs:
      - targets: ['materialize:6875']

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9001']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123'] 