# Configuration for alerts.yml

groups:
  - name: platform_alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is {{ $value }}% (> 5%) for the last 5 minutes

      # Slow Response Time Alert
      - alert: SlowResponseTime
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow response time detected
          description: Average response time is {{ $value }}s (> 1s) for the last 5 minutes

      # High Rate Limiting Alert
      - alert: HighRateLimiting
        expr: sum(rate(rate_limit_hits_total[5m])) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High rate limiting detected
          description: Rate limit hits are {{ $value }} per second for the last 5 minutes

      # Low Cache Hit Rate Alert
      - alert: LowCacheHitRate
        expr: sum(rate(cache_hits_total[5m])) / (sum(rate(cache_hits_total[5m])) + sum(rate(cache_misses_total[5m]))) * 100 < 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Low cache hit rate detected
          description: Cache hit rate is {{ $value }}% (< 50%) for the last 10 minutes

      # Service Health Alert
      - alert: ServiceUnhealthy
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: Service {{ $labels.job }} has been down for more than 1 minute

      # High Database Latency Alert
      - alert: HighDatabaseLatency
        expr: rate(db_query_duration_seconds_sum[5m]) / rate(db_query_duration_seconds_count[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High database latency detected
          description: Database {{ $labels.database }} latency is {{ $value }}s (> 0.1s) for the last 5 minutes

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: Memory usage is {{ $value }}% (> 80%) for the last 5 minutes

      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: CPU usage is {{ $value }}% (> 80%) for the last 5 minutes
