name: data_validation
type: validate
enabled: true
order: 7
config:
  validations:
    user_id:
      type: "int"
      min_value: 1
    email:
      type: "str"
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    age:
      type: "int"
      min_value: 0
      max_value: 150
    status:
      type: "str"
      allowed_values: ["active", "inactive", "pending"]
    description:
      type: "str"
      min_length: 10
      max_length: 1000 