api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

  metrics:
    address: ":8082"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@thedata.io"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: thedata_net
  
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Increase timeouts
serversTransport:
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 30s
    idleConnTimeout: 30s

# Configure default timeouts for all services
http:
  middlewares:
    default-timeouts:
      forwardAuth:
        address: "http://api:8000/api/v1/auth/verify"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User"
          - "X-Auth-Role"
        tls:
          insecureSkipVerify: true

log:
  level: INFO
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

metrics:
  prometheus:
    entryPoint: metrics
    addServicesLabels: true
    addEntryPointsLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

pilot:
  token: ""
